export const possibleFragTags = [
  '#EXTINF',
  '#EXT-X-BYTERANGE',
  '#EXT-X-DISCONTINUITY',
  '#EXT-X-KEY',
  '#EXT-X-MAP',
  '#EXT-X-PROGRAM-DATE-TIME',
  '#EXT-X-DATERANGE',
]

export const possiblePlaylistTags = [
  '#EXTM3U',
  '#EXT-X-VERSION',
  '#EXT-X-TARGETDURATION',
  '#EXT-X-MEDIA-SEQUENCE',
  '#EXT-X-DISCONTINUITY-SEQUENCE',
  '#EXT-X-ENDLIST',
  '#EXT-X-PLAYLIST-TYPE',
  '#EXT-X-I-FRAMES-ONLY',
  '#EXT-X-INDEPENDENT-SEGMENTS',
  '#EXT-X-START',
]
